#!/bin/bash
/show/listecho "Install mjpeg-streamer as supervisor service"
/system/install supervisor
cat <<\EOF > /etc/supervisor/conf.d/mjpegstreamer.conf
[program:mjpegstreamer]
command=/do/mjpeg-streamer/stream
autostart=true
autorestart=true
stdout_logfile=/var/log/mjpegstreamer.log
redirect_stderr=true
EOF
supervisorctl reread
supervisorctl update
